---
title: "Week 9 Code Along & Challenge"
author: "Wong Zi Xin"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=TRUE,echo=TRUE}
library(tidyverse) 
tidydata <- tribble(
  ~country, ~year, ~cases, ~population, 
  "Afghanistan", 1999, 745, 19987071,
  "Afghanistan", 2000, 2666, 20595360, 
  "Brazil", 1999, 37737, 172006362,
  "Brazil", 2000, 80488, 174504898,
  "China", 1999, 212258, 1272915272,
  "China", 2000, 213766, 1280428583)

tidydata
```

```{r, eval=TRUE,echo=TRUE}
nontidydata <- tribble(
  ~country, ~year, ~rate, 
  "Afghanistan", 1999, "745/19987071",
  "Afghanistan", 2000, "2666/20595360", 
  "Brazil", 1999, "37737/172006362",
  "Brazil", 2000, "80488/174504898",
  "China", 1999, "212258/1272915272",
  "China", 2000, "213766/1280428583")

nontidydata
```

```{r, eval=TRUE,echo=TRUE}
nontidydata
```

```{r, eval=TRUE,echo=TRUE}
tidieddata <- nontidydata %>% 
  separate(rate, into = c("cases", 
                          "population"),
                            sep = "/")

tidieddata
```

```{r, eval=TRUE,echo=TRUE}
newtidieddata <- tidieddata %>% 
  pivot_longer(
    cols = cases:population, 
    names_to = "measurement",
    values_to = "value"
  )

newtidieddata
```

```{r, eval=TRUE,echo=TRUE}
df <- tribble(
  ~id, ~bp1, ~bp2,
  "A", 100, 120,
  "B", 140, 115,
  "C", 120, 125
)
df
```

```{r, eval=TRUE,echo=TRUE}
df %>% 
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
  )
```

```{r, eval=TRUE,echo=TRUE}
newtidieddata
```

```{r, eval=TRUE,echo=TRUE}
newtidieddata %>% 
  pivot_wider(names_from = "measurement",
              values_from = "value")
```

```{r, eval=TRUE,echo=TRUE}
df <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1", 100,
  "B", "bp1", 140,
  "B", "bp2", 115,
  "A", "bp2", 120,
  "A", "bp3", 105
  )
df
```

```{r, eval=TRUE,echo=TRUE}
df %>% 
  pivot_wider(
    names_from = measurement, 
    values_from = value
  )
```

```{r, eval=TRUE,echo=TRUE}
billboard_dataset <- billboard %>%
  pivot_longer(cols = starts_with("wk"), 
               names_to = "week", 
               values_to = "rank", 
               values_drop_na = TRUE) %>%
  mutate(week = parse_number(week))

ggplot(billboard_dataset, aes(x = week, y = rank)) +
  geom_line() +
  labs(x = "Week", y = "Rank") +
  theme_minimal()
```

```{r, eval=TRUE,echo=TRUE}
patient_exp <- cms_patient_experience %>%
  pivot_wider(
    id_cols = starts_with("org"),
    names_from = measure_cd,
    values_from = prf_rate
  )

patient_exp
```


